[package]
name = "secondary_adapter_notifier_tokio_channel"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
async-trait = {workspace = true}
domain = {path = "../domain" }
