//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use super::sea_orm_active_enums::EndpointAction;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "endpoint_action_settings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub endpoint_id: i32,
    pub action_type: EndpointAction,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub payload: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::public_endpoint::Entity",
        from = "Column::EndpointId",
        to = "super::public_endpoint::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PublicEndpoint,
}

impl Related<super::public_endpoint::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PublicEndpoint.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
