//! `SeaORM` Entity, @generated by sea-entity-codegen 1.1.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "path")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", unique)]
    pub url: String,
    pub created_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::received_requests::Entity")]
    ReceivedRequests,
}

impl Related<super::received_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReceivedRequests.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
