//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use super::sea_orm_active_enums::HttpMethod;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "public_request")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub endpoint_id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub body: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub host: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub headers: Json,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub query_params: Option<Json>,
    pub http_method: HttpMethod,
    pub timestamp: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::public_endpoint::Entity",
        from = "Column::EndpointId",
        to = "super::public_endpoint::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PublicEndpoint,
}

impl Related<super::public_endpoint::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PublicEndpoint.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
