//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "endpoint_action")]
pub enum EndpointAction {
    #[sea_orm(string_value = "custom_response")]
    CustomResponse,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "http_method")]
pub enum HttpMethod {
    #[sea_orm(string_value = "get")]
    Get,
    #[sea_orm(string_value = "post")]
    Post,
    #[sea_orm(string_value = "put")]
    Put,
    #[sea_orm(string_value = "delete")]
    Delete,
    #[sea_orm(string_value = "patch")]
    Patch,
    #[sea_orm(string_value = "head")]
    Head,
    #[sea_orm(string_value = "connect")]
    Connect,
    #[sea_orm(string_value = "options")]
    Options,
    #[sea_orm(string_value = "trace")]
    Trace,
}
