[package]
name = "domain"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.86"
dyn-clone = "1.0.18"

serde = { workspace = true }
serde_json = { workspace = true }
uuid = {workspace = true}
chrono = {workspace = true}